services:
  # Caching service (Redis container)
  redis:
    image: redis:alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    restart: always

  # API server service (Express container)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: url-shortener-backend
    ports:
      - "5001:5001"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - PORT=5001
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: always
